### ISSUE TITLE
Update citation

### ISSUE THREAD

**Issue by SantiagoBautista** [RdNetwork/Declarative-LOD-Anonymizer-draft#1]
Hi,
In the "Use this work" section, the README reads "This will be updated once the ISWC2018 detailed proceedings are published."

If I am not mistaken, the ISWC2018 proceedings have been published, so you can update the citation ;)

Cheers,
Santiago Bautista

**Comment by RdNetwork** [comment]
Hi,

Thanks for the heads up. I had actually already updated some of it but either forgot to push them or did not update them completely.
This is now fixed.

Have a nice day

Remy
